---
- name: Ensure Fail2Ban packages are installed
  ansible.builtin.package:
    name: "{{ fail2ban_packages }}"
    state: present
    update_cache: true

- name: Ensure Fail2Ban configuration directory exists
  ansible.builtin.file:
    path: "{{ fail2ban_cfg_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Write managed settings to DEFAULT section
  community.general.ini_file:
    path: "{{ fail2ban_cfg_dir }}/jail.local"
    section: DEFAULT
    option: "{{ fail2ban_varsmap[item] }}"
    value: >-
      {{ lookup('vars', item, default='') | string | lower
         if lookup('vars', item, default='') | type_debug == 'bool'
         else lookup('vars', item, default='') }}
    mode: '0644'
    owner: root
    group: root
  when:
    - item in fail2ban_varsmap
    - lookup('vars', item, default='') | string | trim | length > 0
    - not (item == 'f2b_bantime_maxtime' and lookup('vars', item, default=0) | int == 0)
  notify: Restart fail2ban
  loop: "{{ fail2ban_default_settings }}"

- name: Remove unmanaged optional DEFAULT settings
  community.general.ini_file:
    path: "{{ fail2ban_cfg_dir }}/jail.local"
    section: DEFAULT
    option: "{{ fail2ban_varsmap[item] }}"
    mode: '0644'
    owner: root
    group: root
    state: absent
  when:
    - item in fail2ban_varsmap
    - >-
      lookup('vars', item, default='') | string | trim | length == 0 or
      (item == 'f2b_bantime_maxtime' and lookup('vars', item, default=0) | int == 0)
  notify: Restart fail2ban
  loop: "{{ fail2ban_optional_default_settings }}"

- name: Write settings to specific jail sections
  community.general.ini_file:
    path: "{{ fail2ban_cfg_dir }}/jail.local"
    section: "{{ item.0.name }}"
    option: "{{ item.1.key }}"
    value: "{{ item.1.value | default(omit) }}"
    mode: '0644'
    owner: root
    group: root
    state: "{{ item.1.state | default('present') }}"
  loop: "{{ f2b_jails | subelements('settings') }}"
  loop_control:
    label: "Section: {{ item.0.name }}, Key: {{ item.1.key }}"
  notify: Restart fail2ban

- name: Ensure Fail2Ban service is enabled and started
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
  when: f2b_manage_service
