---
# tasks file for guidugli.fail2ban

- name: Run semantic input validation
  ansible.builtin.import_tasks: assert.yml

- name: Install and configure Fail2Ban
  ansible.builtin.import_tasks: fail2ban.yml

- name: Apply optional systemd hardening
  ansible.builtin.import_tasks: systemd_secure.yml
  when: f2b_systemd_secure
